version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - IoTS-Project2
      
  pg4admin:
    image: dpage/pgadmin4
    container_name: pg4admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
    networks:
      - IoTS-Project2
    depends_on:
      - postgres
      
   sensor:
    image: sensor
    container_name: sensor
    networks:
      - IoTS-Project2
    depends_on:
      - postgres
    
    mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
        - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - IoTS-Project2
      
    analytics:
    image: analytics
    container_name: analytics
    networks:
      - IoTS-Project2
    depends_on:
      - mosquitto
      
    eventinfo:
    image: eventinfo
    container_name: eventinfo
    ports:
      - "5117:80"
    networks:
      - IoTS-Project2
    depends_on:
      - mosquitto
  
networks:
  IoTS-Project2:
    driver: bridge